# Generated by Django 4.1 on 2022-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_base_index_rename_flashcards_flashcard_delete_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
